### ISSUE TITLE
Open hangs on macOS Catalina

### ISSUE THREAD

**Issue by donn** [yeokm1/SwiftSerial#16]
I'm on macOS Catalina 10.15.1.

GNU screen works fine with /dev/tty.usbserial-14640, but try serialPort.openPort() hangs

**Comment by yeokm1** [comment]
I mentioned in the readme.

```For Macs, this library currently only works with the /dev/cu.* ports instead of the /dev/tty.*. I have enabled blocking on the serial port to prevent high CPU usage which will prevent the /dev/tty.* from working. Read more about the differences between the two here. If there is a problem, open an issue describing your situation and let me look into it.```

Do you need *.tty ports only?

**Comment by donn** [comment]
Ah. Apologies. I missed that.

On the bright side I can confirm it works on Catalina perfectly with `cu` ports. Thank you so much for the prompt reply.

**Comment by yeokm1** [comment]
@donn No problem!
