### ISSUE TITLE
Newer macOS serial entitlement

### ISSUE THREAD

**Issue by doHernandezM** [yeokm1/SwiftSerial#18]
Awesome code, thanks for making this!
It looks like in macOS Big Sur, and possibly earlier, the USB entitlement is not necessary and has been replaced by a serial one, "com.apple.security.device.serial" However, this needs to be manually added to the "YourApp.entitlements" file in the Xcode project, there is no checkbox for it. Hope that helps someone else!

**Comment by yeokm1** [comment]
Thanks for the tip. Let me update the readme soon. Will close this when done.

**Comment by yeokm1** [comment]
Added instruction in this commit https://github.com/yeokm1/SwiftSerial/commit/4e46944053c9dd5b0340aeed4772d68bc371c04e
