### ISSUE TITLE
Best use case for project?

### ISSUE THREAD

**Issue by utdrmac** [yeokm1/SwiftSerial#19]
Hello. I'm relatively new to macos (not iOS) programming. I have a USB device (crypto hardware wallet) that i'd like to interface with in my app. Is this library suited for such a task? Do you have any examples for writing/reading data to such a device (vs your example of serial/baud communication)? Thanks!

**Comment by yeokm1** [comment]
Hi @utdrmac , to be honest, I don't think it will work.

This library is meant for serial devices in general including USB-serial adapters. Unless your USB crypto hardware wallet is a USB-serial device, this library is highly unlikely to work with it.

Your USB hardware wallet probably needs a custom driver.

**Comment by utdrmac** [comment]
Thanks. I've been reading the developer documentation on the device and I can interact with it using HID standards. They publish the specs to the binary protocol so looks like I'll be the one to write the custom driver. Any hints towards Swift/XCode/Macos USB communications you can share?

**Comment by yeokm1** [comment]
I'm don't know how to write a Mac USB driver sorry!
