### ISSUE TITLE
Always Getting failedToOpen Error

### ISSUE THREAD

**Issue by EmreSURK** [yeokm1/SwiftSerial#9]
Hello,
I m trying to communicate a Mac app with Arduino Mega.
I tried that command and worked perfectly:  screen /dev/cu.usbmodem14201 9600 -L 
The code I use is below;

`  let portName = "/dev/cu.usbmodem14201";
    
    override func viewDidLoad() {
        super.viewDidLoad()

        do {
            let serialPort: SerialPort = SerialPort(path: portName)
            serialPort.setSettings(receiveRate: .baud9600, transmitRate: .baud9600, minimumBytesToRead: 1)
            try serialPort.openPort() //openPort(toReceive: true, andTransmit: true)
            let str = try serialPort.readString(ofLength: 5)
            print(str)
        } catch {
            print(error.localizedDescription)
            print(error)
            print("catch ")
        }
    }
`
Any idea?

**Comment by dnadoba** [comment]
Mac Apps are sandboxed and you need the USB entitlement. To add this entitlement to your app, enable the App Sandbox capability in Xcode, and under Hardware, select USB.
<img width="667" alt="Screenshot 2019-04-08 at 00 49 08" src="https://user-images.githubusercontent.com/5688874/55690960-6ff8fb00-5998-11e9-9df6-7e3ebe50e19a.png">

**Comment by EmreSURK** [comment]
I ll try that.
Maybe you can add that to document, thanks.

**Comment by EmreSURK** [comment]
Hello again,
Thanks for that great repo and your answer.
I added your answer to README file on Mac OS Preparation section and sent a pull request with no conflict to improve the repo. 
I m closing the issue now.
Thanks.

**Comment by noahbkim** [comment]
Hey, was wondering about this exact issue. I've added the USB entitlement but can't get past a -1 file descriptor on `open()`. Maybe does this have to do with permissions on the `cu.*` device? Neither tty. or cu. work, but I can flash to the Arduino no problem.

**Comment by yeokm1** [comment]
@noahbkim I'm not sure the details of your problem. If this is an issue, can you create a new issue and reference this one?

Include all relevant code and project files so I can recreate the issue.

**Comment by attiamohammed** [comment]
@noahbkim Any luck with this issue? I ran into the same issue when I run the above code.

**Comment by yeokm1** [comment]
Hi @attiamohammed  and @noahbkim 

Can you try this solution suggested by @doHernandezM in this issue https://github.com/yeokm1/SwiftSerial/issues/18

`It looks like in macOS Big Sur, and possibly earlier, the USB entitlement is not necessary and has been replaced by a serial one, "com.apple.security.device.serial" However, this needs to be manually added to the "YourApp.entitlements" file in the Xcode project, there is no checkbox for it. Hope that helps someone else!`

**Comment by attiamohammed** [comment]
Thanks a lot. I found the easiest way is to just delete the sandbox from the project. This enables the code to behave normally.
